services:
  web:
    build: .
    container_name: mysportsnest_backend
    ports:
      - "8007:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped

  celery:
    build: .
    container_name: mysportsnest_celery
    volumes:
      - .:/app
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped
    command: celery -A config worker --loglevel=info

  celery_beat:
    build: .
    container_name: mysportsnest_celery_beat
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped
    command: celery -A config beat --loglevel=info

  flower:
    build: .
    container_name: mysportsnest_flower
    ports:
      - "5557:5555"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    entrypoint: []
    command: celery -A config flower --port=5555 --address=0.0.0.0

  db:
    image: postgres:15
    container_name: mysportsnest_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5437:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: mysportsnest_redis
    ports:
      - "6387:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
