# apps/users/middleware.py

class StreakMiddleware:
    """Middleware to update a user's daily consecutive activity streak on incoming requests."""

    def __init__(self, get_response):
        """Initialize middleware with the next response handler.

        Args:
            get_response (callable): The next middleware or view handler in the request pipeline.
        """
        self.get_response = get_response

    def __call__(self, request):
        """Process incoming request and update the authenticated user's streak if applicable.

        Args:
            request (HttpRequest): The Django HTTP request object.

        Returns:
            HttpResponse: The response generated by downstream middleware or views.
        """
        if request.user.is_authenticated and hasattr(request.user, 'streak'):
            request.user.streak.update_streak()
        return self.get_response(request)