# Generated by Django 5.2.11 on 2026-02-19 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('team', 'Team'), ('athlete', 'Athlete'), ('league', 'League')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('sport', models.CharField(choices=[('basketball', 'Basketball'), ('football', 'American Football'), ('soccer', 'Soccer'), ('baseball', 'Baseball'), ('hockey', 'Hockey'), ('cricket', 'Cricket'), ('tennis', 'Tennis'), ('f1', 'Formula 1'), ('mma', 'MMA'), ('golf', 'Golf')], max_length=50)),
                ('api_source', models.CharField(blank=True, max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('logo_url', models.URLField(blank=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('follower_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('has_api_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-follower_count', 'name'],
                'indexes': [models.Index(fields=['type', 'sport'], name='entity_enti_type_4f87c3_idx'), models.Index(fields=['api_source', 'external_id'], name='entity_enti_api_sou_6f216c_idx'), models.Index(fields=['slug'], name='entity_enti_slug_1aa4ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('height_cm', models.IntegerField(blank=True, null=True)),
                ('weight_kg', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('salary_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contract_years_remaining', models.IntegerField(blank=True, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=100)),
                ('instagram_handle', models.CharField(blank=True, max_length=100)),
                ('current_team', models.ForeignKey(blank=True, limit_choices_to={'type': 'team'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_athletes', to='entity.entity')),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_details', to='entity.entity')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_season', models.CharField(blank=True, max_length=20)),
                ('number_of_teams', models.IntegerField(default=0)),
                ('has_playoffs', models.BooleanField(default=False)),
                ('has_divisions', models.BooleanField(default=False)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='league_details', to='entity.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(blank=True, max_length=200)),
                ('venue_city', models.CharField(blank=True, max_length=100)),
                ('venue_capacity', models.IntegerField(blank=True, null=True)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_losses', models.IntegerField(default=0)),
                ('win_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('website_url', models.URLField(blank=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=100)),
                ('youtube_channel_id', models.CharField(blank=True, max_length=100)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_details', to='entity.entity')),
                ('league', models.ForeignKey(blank=True, limit_choices_to={'type': 'league'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='entity.entity')),
            ],
        ),
        migrations.CreateModel(
            name='EntityStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('stat_type', models.CharField(max_length=50)),
                ('stats_data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='entity.entity')),
            ],
            options={
                'ordering': ['-season'],
                'unique_together': {('entity', 'season', 'stat_type')},
            },
        ),
    ]
