# Generated by Django 5.2.11 on 2026-03-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_entity_rss_discovery_done_alter_entity_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
