# Generated by Django 5.2.11 on 2026-05-16 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_add_deduplication_ai'),
        ('entity', '0003_alter_entity_country'),
    ]

    operations = [
    ]
