# Generated by Django 5.2.11 on 2026-05-16 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_merge_20260516_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entitysource',
            name='source',
        ),
        migrations.RemoveField(
            model_name='entitysource',
            name='user_nest',
        ),
        migrations.RemoveField(
            model_name='rsssource',
            name='entities',
        ),
        migrations.RenameIndex(
            model_name='canonicalentity',
            new_name='entity_cano_sport_17e058_idx',
            old_name='entity_canon_sport_0a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='canonicalentity',
            new_name='entity_cano_is_cura_c703b6_idx',
            old_name='entity_canon_is_cur_3d4e5f_idx',
        ),
        migrations.AlterField(
            model_name='canonicalentity',
            name='entity',
            field=models.OneToOneField(help_text='The canonical Entity this canonical refers to', on_delete=django.db.models.deletion.CASCADE, related_name='canonical', to='entity.entity'),
        ),
        migrations.AlterField(
            model_name='canonicalentity',
            name='external_ids',
            field=models.JSONField(default=dict, help_text='JSON: {"api_sports": 541, "balldontlie": 25, "thesportsdb": "133603"}'),
        ),
        migrations.AlterField(
            model_name='canonicalentity',
            name='is_curated',
            field=models.BooleanField(default=False, help_text='True if manually verified by admin'),
        ),
        migrations.AlterField(
            model_name='canonicalentity',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='True if data quality checked'),
        ),
        migrations.AlterField(
            model_name='canonicalentity',
            name='name_variations',
            field=models.JSONField(default=list, help_text='JSON array: ["Real Madrid", "RM", "Real Madrid CF"]'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='canonical_entity',
            field=models.ForeignKey(blank=True, help_text='Points to canonical entity if this is a duplicate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='entity.entity'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, help_text='Normalized (lowercase, no accents) for deduplication', max_length=200),
        ),
        migrations.DeleteModel(
            name='EntitySource',
        ),
        migrations.DeleteModel(
            name='RSSSource',
        ),
    ]
