# Generated by Django 5.2.11 on 2026-07-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0005_remove_entitysource_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canonicalentity',
            name='sport',
            field=models.CharField(choices=[('soccer', 'Soccer'), ('basketball', 'Basketball'), ('american_football', 'American Football'), ('football', 'American Football'), ('baseball', 'Baseball'), ('ice_hockey', 'Ice Hockey'), ('hockey', 'Hockey'), ('cricket', 'Cricket'), ('rugby', 'Rugby'), ('f1', 'Formula 1'), ('formula1', 'Formula 1'), ('tennis', 'Tennis'), ('combat_sports', 'Combat Sports'), ('mma', 'MMA'), ('golf', 'Golf'), ('motorsports', 'Motorsports'), ('esports', 'eSports'), ('handball', 'Handball'), ('volleyball', 'Volleyball')], max_length=50),
        ),
        migrations.AlterField(
            model_name='entity',
            name='sport',
            field=models.CharField(choices=[('soccer', 'Soccer'), ('basketball', 'Basketball'), ('american_football', 'American Football'), ('football', 'American Football'), ('baseball', 'Baseball'), ('ice_hockey', 'Ice Hockey'), ('hockey', 'Hockey'), ('cricket', 'Cricket'), ('rugby', 'Rugby'), ('f1', 'Formula 1'), ('formula1', 'Formula 1'), ('tennis', 'Tennis'), ('combat_sports', 'Combat Sports'), ('mma', 'MMA'), ('golf', 'Golf'), ('motorsports', 'Motorsports'), ('esports', 'eSports'), ('handball', 'Handball'), ('volleyball', 'Volleyball')], max_length=50),
        ),
    ]
