# Generated by Django 5.2.11 on 2026-02-19 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('basketball', 'Basketball'), ('football', 'American Football'), ('soccer', 'Soccer'), ('baseball', 'Baseball'), ('hockey', 'Hockey'), ('cricket', 'Cricket'), ('tennis', 'Tennis'), ('f1', 'Formula 1'), ('mma', 'MMA'), ('golf', 'Golf')], max_length=50)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], db_index=True, default='upcoming', max_length=20)),
                ('status_detail', models.CharField(blank=True, max_length=100)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=200)),
                ('venue_city', models.CharField(blank=True, max_length=100)),
                ('venue_country', models.CharField(blank=True, max_length=100)),
                ('broadcaster', models.CharField(blank=True, max_length=100)),
                ('stream_url', models.URLField(blank=True)),
                ('api_source', models.CharField(blank=True, max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_events', to='entity.entity')),
                ('home_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_events', to='entity.entity')),
                ('league', models.ForeignKey(blank=True, limit_choices_to={'type': 'league'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='league_events', to='entity.entity')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(default='youtube', max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='event.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_type', models.CharField(choices=[('starting', 'Starting XI'), ('substitute', 'Substitute'), ('coach', 'Coach')], max_length=20)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('grid_position', models.CharField(blank=True, max_length=10)),
                ('metadata', models.JSONField(default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='event.event')),
                ('player', models.ForeignKey(limit_choices_to={'type': 'athlete'}, on_delete=django.db.models.deletion.CASCADE, related_name='lineup_appearances', to='entity.entity')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
            ],
        ),
        migrations.CreateModel(
            name='EventPlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats', models.JSONField(default=dict)),
                ('points_or_goals', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='event.event')),
                ('player', models.ForeignKey(limit_choices_to={'type': 'athlete'}, on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_player_stats', to='entity.entity')),
            ],
        ),
        migrations.CreateModel(
            name='EventStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='event.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
            ],
        ),
        migrations.CreateModel(
            name='EventTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('goal', 'Goal'), ('yellow_card', 'Yellow Card'), ('red_card', 'Red Card'), ('substitution', 'Substitution'), ('penalty', 'Penalty'), ('var', 'VAR Decision'), ('injury', 'Injury'), ('timeout', 'Timeout'), ('period_start', 'Period Start'), ('period_end', 'Period End')], max_length=50)),
                ('minute', models.IntegerField()),
                ('extra_minute', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='event.event')),
                ('player', models.ForeignKey(blank=True, limit_choices_to={'type': 'athlete'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_events', to='entity.entity')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
            ],
            options={
                'ordering': ['minute', 'extra_minute'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['sport', 'status', 'start_time'], name='event_event_sport_2f81c1_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_time'], name='event_event_start_t_f57654_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['home_entity', 'start_time'], name='event_event_home_en_41d887_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['away_entity', 'start_time'], name='event_event_away_en_8b975b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('api_source', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='eventlineup',
            unique_together={('event', 'team', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='eventplayerstats',
            unique_together={('event', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='eventstatistics',
            unique_together={('event', 'team')},
        ),
    ]
