# Generated by Django 5.2.11 on 2026-06-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sport',
            field=models.CharField(choices=[('basketball', 'Basketball'), ('football', 'American Football'), ('soccer', 'Soccer'), ('baseball', 'Baseball'), ('hockey', 'Hockey'), ('handball', 'Handball'), ('volleyball', 'Volleyball'), ('cricket', 'Cricket'), ('tennis', 'Tennis'), ('horse_racing', 'Horse Racing'), ('formula1', 'Formula 1'), ('mma', 'MMA'), ('golf', 'Golf')], max_length=50),
        ),
        migrations.AlterField(
            model_name='eventlineup',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
