# Generated by Django 5.2.11 on 2026-07-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_sport_alter_eventlineup_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sport',
            field=models.CharField(choices=[('soccer', 'Soccer'), ('basketball', 'Basketball'), ('american_football', 'American Football'), ('football', 'American Football'), ('baseball', 'Baseball'), ('ice_hockey', 'Ice Hockey'), ('hockey', 'Hockey'), ('handball', 'Handball'), ('volleyball', 'Volleyball'), ('cricket', 'Cricket'), ('rugby', 'Rugby'), ('tennis', 'Tennis'), ('horse_racing', 'Horse Racing'), ('f1', 'Formula 1'), ('formula1', 'Formula 1'), ('combat_sports', 'Combat Sports'), ('mma', 'MMA'), ('golf', 'Golf'), ('motorsports', 'Motorsports'), ('esports', 'eSports')], max_length=50),
        ),
    ]
