# Generated by Django 5.2.11 on 2026-04-19 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_dailystreak'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
