# Generated by Django 5.2.11 on 2026-02-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('nba', 'NBA'), ('nfl', 'NFL'), ('mlb', 'MLB'), ('nhl', 'NHL'), ('soccer', 'Soccer'), ('cricket', 'Cricket')], max_length=20)),
                ('external_id', models.CharField(max_length=100)),
                ('home_team', models.CharField(max_length=200)),
                ('away_team', models.CharField(max_length=200)),
                ('home_logo', models.URLField(blank=True)),
                ('away_logo', models.URLField(blank=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('live', 'Live'), ('upcoming', 'Upcoming'), ('completed', 'Completed')], max_length=20)),
                ('status_detail', models.CharField(blank=True, max_length=50)),
                ('start_time', models.DateTimeField()),
                ('raw_data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['sport', 'status'], name='score_lives_sport_430642_idx'), models.Index(fields=['start_time'], name='score_lives_start_t_446e75_idx')],
                'unique_together': {('sport', 'external_id')},
            },
        ),
    ]
