# Generated by Django 5.2.11 on 2026-03-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_alter_livescore_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='livescore',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
