# Generated by Django 5.2.11 on 2026-06-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_livescore_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livescore',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
