# Generated by Django 5.2.11 on 2026-02-19 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('gnews', 'GNews API'), ('youtube', 'YouTube'), ('rss', 'RSS Feed'), ('official', 'Official Source')], max_length=20)),
                ('url', models.URLField(blank=True)),
                ('rss_feed_url', models.URLField(blank=True)),
                ('youtube_channel_id', models.CharField(blank=True, max_length=100)),
                ('youtube_channel_name', models.CharField(blank=True, max_length=200)),
                ('logo_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('article_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('type', 'url'), ('type', 'youtube_channel_id')},
            },
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('image', 'Image'), ('post', 'Social Post')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('url', models.URLField(unique=True)),
                ('url_hash', models.CharField(db_index=True, max_length=64)),
                ('title_hash', models.CharField(db_index=True, max_length=64)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('is_breaking', models.BooleanField(db_index=True, default=False)),
                ('is_trending', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(default=dict)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to='entity.entity')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to='feed.source')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_sources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedItemView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('feed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.feeditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'feed_item')},
            },
        ),
        migrations.CreateModel(
            name='HiddenSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_sources', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.source')),
            ],
            options={
                'unique_together': {('user', 'source')},
            },
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['entity', '-published_at'], name='feed_feedit_entity__5db9fd_idx'),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['content_type', '-published_at'], name='feed_feedit_content_9b1f97_idx'),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['url_hash'], name='feed_feedit_url_has_bc62fd_idx'),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['title_hash', 'published_at'], name='feed_feedit_title_h_fe5ec1_idx'),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['-published_at'], name='feed_feedit_publish_9d7682_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersource',
            unique_together={('user', 'source', 'entity')},
        ),
    ]
