# Generated by Django 5.2.11 on 2026-03-13 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_entity_rss_discovery_done_alter_entity_created_at'),
        ('feed', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feeditemview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='feeditemview',
            name='feed_item',
        ),
        migrations.RemoveField(
            model_name='feeditemview',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['-is_verified', 'name']},
        ),
        migrations.RemoveIndex(
            model_name='feeditem',
            name='feed_feedit_entity__5db9fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='feeditem',
            name='feed_feedit_content_9b1f97_idx',
        ),
        migrations.RemoveIndex(
            model_name='feeditem',
            name='feed_feedit_title_h_fe5ec1_idx',
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='feeditem',
            name='author',
        ),
        migrations.RemoveField(
            model_name='feeditem',
            name='content',
        ),
        migrations.RemoveField(
            model_name='feeditem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='feeditem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='feeditem',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='feeditem',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='feeditem',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='feeditem',
            name='title_hash',
        ),
        migrations.RemoveField(
            model_name='feeditem',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='hiddensource',
            name='hidden_at',
        ),
        migrations.AlterUniqueTogether(
            name='usersource',
            unique_together={('user', 'source')},
        ),
        migrations.AddField(
            model_name='feeditem',
            name='entities',
            field=models.ManyToManyField(blank=True, related_name='feed_items', to='entity.entity'),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hiddensource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='discovery_source',
            field=models.CharField(choices=[('brave', 'Brave Search Discovery'), ('known', 'Known Sports Feed'), ('manual', 'Manually Added')], default='brave', max_length=20),
        ),
        migrations.AddField(
            model_name='source',
            name='domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='source',
            name='entities',
            field=models.ManyToManyField(blank=True, related_name='sources', to='entity.entity'),
        ),
        migrations.AddField(
            model_name='source',
            name='favicon_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='source',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='source',
            name='last_polled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='poll_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='poll_interval_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='source',
            name='rss_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usersource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='is_breaking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='feed.source'),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='url_hash',
            field=models.CharField(db_index=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='source',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usersource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FeedItemView',
        ),
        migrations.RemoveField(
            model_name='source',
            name='article_count',
        ),
        migrations.RemoveField(
            model_name='source',
            name='description',
        ),
        migrations.RemoveField(
            model_name='source',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='source',
            name='rss_feed_url',
        ),
        migrations.RemoveField(
            model_name='source',
            name='type',
        ),
        migrations.RemoveField(
            model_name='source',
            name='url',
        ),
        migrations.RemoveField(
            model_name='source',
            name='youtube_channel_id',
        ),
        migrations.RemoveField(
            model_name='source',
            name='youtube_channel_name',
        ),
        migrations.RemoveField(
            model_name='usersource',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='usersource',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='usersource',
            name='is_active',
        ),
    ]
