# Generated by Django 5.2.11 on 2026-03-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_feeditemview_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='rss_url',
            field=models.URLField(blank=True, default='', null=True, unique=True),
        ),
    ]
