# Generated by Django 5.2.11 on 2026-03-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_source_rss_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='url_hash',
            field=models.CharField(db_index=True, max_length=500, unique=True),
        ),
    ]
