# Generated by Django 5.2.11 on 2026-03-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_feeditem_url_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='url',
            field=models.URLField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='source',
            name='domain',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='source',
            name='favicon_url',
            field=models.URLField(blank=True, max_length=5000),
        ),
    ]
