# Generated by Django 5.2.11 on 2026-05-16 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0005_remove_entitysource_source_and_more'),
        ('feed', '0007_like'),
        ('nest', '0002_alter_userpreferences_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntitySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0, help_text='Higher = shown first in feed')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_selections', to='feed.source')),
                ('user_nest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_sources', to='nest.usernest')),
            ],
            options={
                'ordering': ['-priority', '-added_at'],
                'unique_together': {('user_nest', 'source')},
            },
        ),
        migrations.CreateModel(
            name='RSSSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'La Liga Official'", max_length=200)),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('sport', models.CharField(choices=[('basketball', 'Basketball'), ('football', 'American Football'), ('soccer', 'Soccer'), ('baseball', 'Baseball'), ('hockey', 'Hockey'), ('cricket', 'Cricket'), ('tennis', 'Tennis'), ('f1', 'Formula 1'), ('mma', 'MMA'), ('golf', 'Golf')], help_text='Sport this feed covers', max_length=50)),
                ('keywords', models.JSONField(default=list, help_text='["La Liga", "Spanish Football", "LALIGA"]')),
                ('is_active', models.BooleanField(default=True)),
                ('fetch_interval_hours', models.PositiveIntegerField(default=6)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('fetch_failures', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False, help_text='Admin verified')),
                ('estimated_quality', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entities', models.ManyToManyField(blank=True, help_text='Entities this feed provides news for', related_name='rss_sources', to='entity.entity')),
            ],
            options={
                'ordering': ['sport', 'name'],
                'indexes': [models.Index(fields=['sport', 'is_active'], name='feed_rsssou_sport_811669_idx'), models.Index(fields=['is_verified'], name='feed_rsssou_is_veri_629602_idx')],
            },
        ),
    ]
