# Generated by Django 5.2.11 on 2026-07-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_entitysource_rsssource'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='publisher_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
