# Generated by Django 5.2.11 on 2026-07-04 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_add_publisher_name_to_feeditem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hiddensource',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='hiddensource',
            name='publisher_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='hiddensource',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.source'),
        ),
    ]
