# Generated by Django 5.2.11 on 2026-07-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0005_remove_entitysource_source_and_more'),
        ('feed', '0010_alter_hiddensource_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='content_fetched',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['content_fetched'], name='feed_feedit_content_d92a09_idx'),
        ),
    ]
