# Generated by Django 5.2.11 on 2026-07-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_feeditem_ai_summary_feeditem_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='canonical_url',
            field=models.URLField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='source',
            name='sitemap_url',
            field=models.URLField(blank=True, default='', max_length=5000),
        ),
    ]
