# Generated by Django 5.2.11 on 2026-07-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0006_alter_canonicalentity_sport_alter_entity_sport'),
        ('feed', '0013_alter_rsssource_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='is_breaking',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='views',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['-views', '-published_at'], name='feed_feedit_views_f2daa2_idx'),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['-is_trending', '-views', '-published_at'], name='feed_feedit_is_tren_2b068d_idx'),
        ),
    ]
