# Generated by Django 5.2.11 on 2026-09-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_alter_feeditem_is_breaking_alter_feeditem_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='rss_url',
            field=models.URLField(blank=True, default='', max_length=1000, null=True, unique=True),
        ),
    ]
